repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.23
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run ty check --exit-zero-on-warning
        language: system
        types: [python]
        pass_filenames: false
      - id: commitizen
        name: commitizen
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
