name: Commit lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  commitlint:
    name: Conventional commits
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webiny/action-conventional-commits@v1.4.2
